// This file is generated by Astro DB
declare module 'astro:db' {
	export const Usuarios: import("@astrojs/db/runtime").Table<
		"Usuarios",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Usuarios","primaryKey":true}},"nombre":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"nombre","collection":"Usuarios","primaryKey":false,"optional":false}},"userName":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"userName","collection":"Usuarios","primaryKey":false,"optional":false}},"correo":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"correo","collection":"Usuarios","primaryKey":false,"optional":false}},"password":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"password","collection":"Usuarios","primaryKey":false,"optional":false}},"role":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"role","collection":"Usuarios","primaryKey":false,"optional":false}}}
	>;
	export const News: import("@astrojs/db/runtime").Table<
		"News",
		{"id":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"News","primaryKey":true}},"userId":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"userId","collection":"News","primaryKey":false,"optional":false,"references":{"type":"number","schema":{"unique":false,"deprecated":false,"name":"id","collection":"Usuarios","primaryKey":true}}}},"titulo":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"titulo","collection":"News","primaryKey":false,"optional":false}},"contenido":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"contenido","collection":"News","primaryKey":false,"optional":false}},"link":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"link","collection":"News","primaryKey":false,"optional":false}},"fecha":{"type":"date","schema":{"optional":false,"unique":false,"deprecated":false,"name":"fecha","collection":"News"}}}
	>;
}
